config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "localhost:3000"

  #welcome controller, this handles static content
  #TODO: add an about page!
  root 'welcome#index'
  get '/about', to: 'welcome#about'

  resources :casinos do
    resources :products
  end

  #users
  resources :users
  get '/signup', to: 'users#new'

  #orders
  resources :orders, only: [:index, :show, :create]

  #deliverers
  get  '/deliverers',        to: 'welcome#deliverers'
  get  '/deliverers/signup', to: 'deliverer#new'
  post '/deliverers/signup', to: 'deliverer#create'

  #session
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #cart_products
  get    '/cart',             to: 'cart_products#index'
  post   '/cart',             to: 'cart_products#create'
  delete '/cart',             to: 'cart_products#destroy'
  put    '/cart/:product_id', to: 'cart_products#update'
  get    '/cart_count',       to: 'cart_products#count'
end

app/models/casino.rb
class Casino < ApplicationRecord
  has_many :products,
  dependent: :destroy

  validates :nombre, presence: true, length: {minimum: 3}
  validates :tipocomida, presence: true
  validates :rangoprecio, presence: true,length: {maximum: 3}, format: { with: /\A[$]+\z/, message: "Solo se permite el caracter '$'"}
  validates :ubicacion, presence: true
end

app/controllers/casinos_controller.rb
class CasinosController < ApplicationController

  def index
    @casinos = Casino.all
    if @casinos.empty?
      flash.now[:info] = "There are no casinos"
    end
  end

  def show
    @casino = Casino.find(params[:id])
  end

  def new
    @casino = Casino.new
  end

  def edit
    @casino = Casino.find(params[:id])
  end

  def create
    @casino = Casino.new(casino_params)

    if @casino.save
      redirect_to @casino
    else
      render 'new'
    end
  end

  def update
  @casino = Casino.find(params[:id])

  if @casino.update(casino_params)
    redirect_to @casino
  else
    render 'edit'
  end
end

def destroy
  @casino = Casino.find(params[:id])
  @casino.destroy

  redirect_to casinos_path
end

  private
    def casino_params
      params.require(:casino).permit(:nombre, :tipocomida, :rangoprecio, :ubicacion)
    end
end

app/helpers/casinos_helper.rb
module CasinosHelper
end

app/views/casinos/_casinos_table.html.haml
- btn_html_attributes = { class: ["btn", "btn-outline-primary", "btn-sm"] }

%table.table.table-hover.table-bordered.shadow-sm
  %trhead
    %tr
      %th{:scope => "col"} Nombre
      %th{:scope => "col"} Tipo de comida
      %th{:scope => "col"} Rango de precio
      %th{:scope => "col"} Ubicacion
  %tbody
    - @casinos.each do |casino|
      %tr.clickable-row{"data-href": casino_path(casino)}
        %td= casino.nombre
        %td= casino.tipocomida
        %td= casino.rangoprecio
        %td= casino.ubicacion
        - if is_admin?
          %td{:align => "center"}
            .btn-group
              = link_to 'Editar', edit_casino_path(casino), btn_html_attributes
              = link_to 'Eliminar', casino_path(casino), |
                {                                        |
                  method: :delete,                       |
                  data: { confirm: '¿Estas seguro/a?' }, |
                  class: btn_html_attributes[:class]     |
                }                                        |

app/views/casinos/_form.html.erb
<%= form_with model: @casino, local: true do |form| %>

  <!-- TODO: make this appear in a flash message in the layout -->
  <% if @casino.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@casino.errors.count, "error") %> prohibited
        this casino from being saved:
      </h2>
      <ul>
        <% @casino.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, {class: "form-control"} %>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label "Tipo de Comida" %>
      <%= form.text_field :tipocomida, {class: "form-control"} %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :'Rango de precio' %>
    <%= form.text_field :rangoprecio, {class: "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :ubicacion %>
    <%= form.text_field :ubicacion, {class: "form-control"} %>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= link_to 'Volver', :back, class: ["form-control", "btn", "btn-primary"]%>
    </div>
    <div class="col-md-6">
      <% if @submit_text %>
        <%= form.submit @submit_text, class: ["form-control", "btn", "btn-primary"] %>
      <% else %>
        <%= form.submit class: ["form-control", "btn", "btn-primary"] %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/casinos/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Editar casino</h1>
  </div>
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/casinos/index.html.haml
- btn_html_attributes = { class: ["btn", "btn-outline-primary"] }

.container
  .row
    %p.lead.display-4 Listado de casinos
  = render 'shared/admin_panel' do
    .btn-group
      = link_to 'Nuevo casino', new_casino_path, btn_html_attributes
  - if @casinos.any?
    = render 'casinos_table'

app/views/casinos/new.html.erb
<div class="container">
  <div class="row">
    <h1>Nuevo Casino</h1>
  </div>
  <div class="row">
    <%= render 'form' %>
  </div>
  <div class="row">
    <%= link_to 'Volver', casinos_path %>
  </div>
</div>

app/views/casinos/show.html.haml
- btn_html_attributes = { class: ["btn", "btn-outline-primary", "btn-sm"] }

.container
  = render 'shared/admin_panel' do
    .btn-group
      = link_to 'Nuevo Producto', new_casino_product_path(@casino), btn_html_attributes
  .row
    %h1= @casino.nombre
  .row
    %table.table.table-bordered
      %trhead
        %tr
          %th{scope: "col"} Tipo de comida
          %th{scope: "col"} Rango de precio
          %th{scope: "col"} Ubicacion
      %tbody
        %tr
          %td= @casino.tipocomida
          %td= @casino.rangoprecio
          %td= @casino.ubicacion
          - if is_admin?
            %td{align: "center"}
              .btn-group
                = link_to 'Editar', edit_casino_path(@casino), btn_html_attributes
  .row
    %h1 Productos
  .row
    = render 'products/product_list', products: @casino.products
  .row
    = link_to 'Volver', casinos_path, class: ["btn", "btn-primary"]