config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "localhost:3000"

  #welcome controller, this handles static content
  #TODO: add an about page!
  root 'welcome#index'
  get '/about', to: 'welcome#about'

  resources :casinos do
    resources :products
  end

  #users
  resources :users
  get '/signup', to: 'users#new'

  #orders
  resources :orders, only: [:index, :show, :create]

  #deliverers
  get  '/deliverers',        to: 'welcome#deliverers'
  get  '/deliverers/signup', to: 'deliverer#new'
  post '/deliverers/signup', to: 'deliverer#create'

  #session
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #cart_products
  get    '/cart',             to: 'cart_products#index'
  post   '/cart',             to: 'cart_products#create'
  delete '/cart',             to: 'cart_products#destroy'
  put    '/cart/:product_id', to: 'cart_products#update'
  get    '/cart_count',       to: 'cart_products#count'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :casino

  validates :name, presence: true
  validates :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    redirect_to casino_path(casino_params)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @casino = Casino.find(casino_params)
    @product = Product.new(casino_id: @casino[:id])
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product[:casino_id] = params[:casino_id]

    respond_to do |format|
      if @product.save
        flash[:success] = "Producto creado exitosamente."
        format.html { redirect_to casino_path(casino_params) }
        format.json { render :show, status: :created, location: @product }
      else
        flash[:danger] = "Error en la creacion del producto"
        format.html { redirect_to new_casino_product_path }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        flash[:success] = "Producto editado exitosamente."
        format.html { redirect_to casino_product_path }
        format.json { render :show, status: :ok, location: @product }
      else
        flash.now[:danger] = "Error en la edicion del producto"
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      flash[:success] = "Producto eliminado exitosamente."
      format.html { redirect_to casino_path(casino_params) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :casino_id)
    end

    def casino_params
      params.require(:casino_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_to_cart_form.html.haml
.btn-group
  = form_with(url: cart_path) do |form|
    .input-group
      = form.hidden_field :product_id, value: product.id
      .input-group-prepend.input-group-text
        cantidad
      = form.number_field "quantity", {value: 1, class: ["input-group-append", "form-control", "col-sm-2"]}
      .input-group-append
        = form.submit "Agregar al carrito :3", class: ["btn", "btn-outline-primary"]

app/views/products/_form.html.haml
.col-md-6
  = form_with(model: product, url: ok_url, local: true) do |form|
    - if product.errors.any?
      #error_explanation
        %h2
          = pluralize(product.errors.count, "error")
          prohibited this product from being saved:
        %ul
          - product.errors.full_messages.each do |message|
            %li= message
    .form-group
      = form.label :name
      = form.text_field :name, {class: "form-control"}
    .form-group
      = form.label :price
      = form.text_field :price, {class: "form-control"}
    .row
      .col-md-6
        = link_to 'Volver', :back, class: ["btn", "btn-primary", "form-control"]
      .col-md-6
        = form.submit class: ["btn", "btn-primary", "form-control"]

app/views/products/_product_list.html.haml
- btn_html_attributes = { class: ["btn", "btn-outline-primary", "btn-sm"] }

%table.table.table-bordered
  %thead
    %tr
      %th Nombre
      %th Precio
  %tbody
    - products.each do |product|
      %tr
        %td= product.name
        %td= product.price
        %td{align: "center"}
          = render 'products/add_to_cart_form', product: product
        - if is_admin?
          %td{align: "center"}
            .btn-group
              = link_to 'Edit', edit_casino_product_path(product[:casino_id], product), btn_html_attributes
              = link_to 'Destroy', casino_product_path(product[:casino_id], product), |
                {                                                                     |
                  method: :delete,                                                    |
                  data: {                                                             |
                    confirm: 'Seguro quieres borrar este producto?, se ve rico :9'    |
                  },                                                                  |
                  class: btn_html_attributes[:class]                                  |
                }                                                                     |

app/views/products/edit.html.haml
%h1 Editando Producto

= render 'form', product: @product, ok_url: casino_product_path

app/views/products/index.html.erb
<h1>Products</h1>

<%= render 'product_list', products: @products %>


<%= link_to 'New Product', new_casino_product_path %>

app/views/products/new.html.haml
.container
  .row
    %h1
      Nuevo producto para: #{@casino[:nombre]}
  .row
    = render 'form', product: @product, ok_url: casino_products_path

app/views/products/show.html.haml
.container

  %h1 Productos de #{@product.casino[:nombre]}

  %table.table.table-bordered

    %thead
      %tr
        %th Nombre
        %th Precio

    %tbody
      %tr
        %td= @product.name
        %td= @product.price

        %td{align: "center"}
          = render 'add_to_cart_form', product: @product

        - if is_admin?
          %td{align: "center"}
            .btn-group
              = link_to 'Editar', edit_casino_product_path(@product[:casino_id]), class: "btn btn-outline-primary"
  = link_to 'Volver', casino_path(@product[:casino_id]), class: "btn btn-primary"