config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "localhost:3000"

  #welcome controller, this handles static content
  #TODO: add an about page!
  root 'welcome#index'
  get '/about', to: 'welcome#about'

  resources :casinos do
    resources :products
  end

  #users
  resources :users
  get '/signup', to: 'users#new'

  #orders
  resources :orders, only: [:index, :show, :create]

  #deliverers
  get  '/deliverers',        to: 'welcome#deliverers'
  get  '/deliverers/signup', to: 'deliverer#new'
  post '/deliverers/signup', to: 'deliverer#create'

  #session
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #cart_products
  get    '/cart',             to: 'cart_products#index'
  post   '/cart',             to: 'cart_products#create'
  delete '/cart',             to: 'cart_products#destroy'
  put    '/cart/:product_id', to: 'cart_products#update'
  get    '/cart_count',       to: 'cart_products#count'
end

app/views/layouts/_flash.html.haml
= content_tag :div, message, class: ["alert", "alert-"+name]

app/views/layouts/_flash_messages.html.haml
.container-fluid
  - flash.each do |name, msg|
    - if msg.is_a? Array
      - msg.each do |m|
        .row
          = render 'shared/flash', message: m, name: name
    - else
      = render 'shared/flash', message: msg, name: name

app/views/layouts/_main_menu.html.haml
%nav.navbar.navbar-fixed-top.navbar-expand-lg.navbar-dark.bg-dark
  .container
    / brand
    = link_to "UTA Delivery", root_path, class: "navbar-brand"

    / toggle button
    %button.navbar-toggler{"aria-controls" => "navbarText",
    "aria-expanded" => "false",
    "aria-label" => "Toggle navigation",
    "data-target" => "#navbarText",
    "data-toggle" => "collapse",
    type: "button"}
      %span.navbar-toggler-icon

    / main buttons
    - link_html_attributes = {class: ["nav-link"]}
    #navbarText.navbar-collapse.collapse
      %ul.navbar-nav
        %li.nav-item
          = link_to "Casinos", casinos_path, link_html_attributes
        %li.nav-item
          = link_to "Repartidores", deliverers_signup_path, link_html_attributes
        %li.nav-item
          = link_to "Quienes Somos?", about_path, link_html_attributes
    .btn-group
      = link_to cart_path, class: ["btn", "btn-secondary", "btn-sm"] do
        %i.fa.fa-shopping-cart.text-light
        %span#shopping_cart_counter

      -if logged_in?
        %button.btn.btn-secondary.btn-sm.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
          = current_user.name
        .dropdown-menu.dropdown-menu-right
          %button.dropdown-item
            = link_to "Perfil", current_user
          %button.dropdown-item{type: "button"}
            = link_to "Ordenes", orders_path
          .dropdown-divider
          %button.dropdown-item{type: "button"}
            = link_to "Salir", logout_path, method: :delete
      - else
        = link_to login_path, class: ["btn", "btn-secondary", "btn-sm"] do
          Entrar

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Utadelivery
    = csrf_meta_tags
    = csp_meta_tag
    / Required meta tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/main_menu'
    .container-fluid.mt-3
      .row
        = render 'layouts/flash_messages'
      .row
        .container-fluid
          = yield